// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemaPizzaria.Infraestrutura.Database;

#nullable disable

namespace sistemaPizzaria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250311230042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("sistemaPizzaria.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("sistemaPizzaria.Dominio.Entidades.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("NomeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaEscolhidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NomeID");

                    b.HasIndex("PizzaEscolhidaId");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("sistemaPizzaria.Dominio.Entidades.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("sistemaPizzaria.Dominio.Entidades.Pedido", b =>
                {
                    b.HasOne("sistemaPizzaria.Dominio.Entidades.Cliente", "Nome")
                        .WithMany()
                        .HasForeignKey("NomeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistemaPizzaria.Dominio.Entidades.Pizza", "PizzaEscolhida")
                        .WithMany()
                        .HasForeignKey("PizzaEscolhidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nome");

                    b.Navigation("PizzaEscolhida");
                });
#pragma warning restore 612, 618
        }
    }
}
